"""add cloudinary_public_id to skin_concerns

Revision ID: 07244c98c0f6
Revises: bdec962eaa7c
Create Date: 2026-08-22 03:40:36.798275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07244c98c0f6'
down_revision = 'bdec962eaa7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_concerns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_concerns', schema=None) as batch_op:
        batch_op.drop_column('cloudinary_public_id')

    # ### end Alembic commands ###
