"""add step_groups and drop hair step type

Revision ID: 2a735e468547
Revises: 46f80398af62
Create Date: 2026-08-22 05:13:14.983923

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a735e468547'
down_revision = '46f80398af62'
branch_labels = None
depends_on = None

step_groups_table = sa.table(
    "step_groups",
    sa.column("id", sa.String),
    sa.column("key", sa.String),
    sa.column("label", sa.String),
    sa.column("description", sa.Text),
    sa.column("cloudinary_public_id", sa.String),
    sa.column("step_type", sa.String),
    sa.column("position", sa.Integer),
)

SEED_ROWS = [
    ("prep", "Step 1: Prep", "cleanser", 0),
    ("treat", "Step 2: Treat", "serum", 1),
    ("seal", "Step 3: Seal", "barrier_cream", 2),
    ("protect", "Step 4: Protect", "spf", 3),
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('step_type', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        step_groups_table,
        [
            {
                "id": str(uuid.uuid4()),
                "key": key,
                "label": label,
                "description": None,
                "cloudinary_public_id": None,
                "step_type": step_type,
                "position": position,
            }
            for key, label, step_type, position in SEED_ROWS
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_groups')
    # ### end Alembic commands ###
