"""add user profile settings and expose order item ids

Revision ID: bdec962eaa7c
Revises: b1ee6a3d7951
Create Date: 2026-08-22 02:01:07.448944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdec962eaa7c'
down_revision = 'b1ee6a3d7951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_shipping_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('default_shipping_address_line1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('default_shipping_address_line2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('default_shipping_city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('default_shipping_country', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('default_shipping_postal_code', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('default_shipping_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_shipping_phone')
        batch_op.drop_column('default_shipping_postal_code')
        batch_op.drop_column('default_shipping_country')
        batch_op.drop_column('default_shipping_city')
        batch_op.drop_column('default_shipping_address_line2')
        batch_op.drop_column('default_shipping_address_line1')
        batch_op.drop_column('default_shipping_name')

    # ### end Alembic commands ###
