"""add delivery_proof_public_id to orders

Revision ID: f36c3194ac93
Revises: edf66b16608a
Create Date: 2026-08-20 18:45:17.029363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36c3194ac93'
down_revision = 'edf66b16608a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_proof_public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_proof_public_id')

    # ### end Alembic commands ###
